route:
  repeat_interval: 30m
  receiver: "sms-notifications"
  routes:
    - receiver: "email-notifications"
      group_wait: 30s
      match_re:
        severity: critical|warning
      continue: true

    - receiver: "sms-notifications"
      group_wait: 30s
      match_re:
        severity: critical
      continue: true

receivers:
  - name: "email-notifications"
    email_configs:
      - to: h.naimaei@gmail.com
        from: yourmail@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: yourmail@gmail.com
        auth_identity: yourmail@gmail.com
        auth_password: xxxxxxxxxxxxxxxxxx
        # create your own auth_password => https://support.google.com/mail/answer/185833?hl=en
        send_resolved: true

  - name: "sms-notifications"
    webhook_configs:
      - url: http://my-api/api/notify/send
        send_resolved: true
